### ISSUE TITLE
model test for User Model

### ISSUE THREAD

**Issue by adwait-thattey** [hardlyhuman/TFExplorer#16]
Please add tests for user model which checks that user objects are getting created, updated, deleted properly

**Comment by masterashu** [comment]
Will do it.

**Comment by masterashu** [comment]
One thing I noticed, `email` field by default allows blank and is not unique, I believe it will be best to make it **unique** and **required**.

**Comment by adwait-thattey** [comment]
Yes. Please do.

**Comment by adwait-thattey** [comment]
PR #23 Merged
