### ISSUE TITLE
Serializers for API and APIVariant

### ISSUE THREAD

**Issue by adwait-thattey** [hardlyhuman/TFExplorer#19]
Please make 2 serializers for API and APIVariant that allow to create, update, retrieve, delete those model objects.

**Comment by masterashu** [comment]
On it.

**Comment by adwait-thattey** [comment]
@Prahitha is making changes to model names. You may have to make a couple of changes after her PR

**Comment by masterashu** [comment]
Sure

**Comment by adwait-thattey** [comment]
PR #21 has been merged. Please continue. Also you will need to rebase

**Comment by masterashu** [comment]
I think we have to make every field Non-Nullable. The current models allows null values in fields (null=True, by default).
https://github.com/hardlyhuman/TFExplorer/blob/9285eeaee8c46f8fea1faeb0a2284719a6ad171f/base/models.py#L7-L17
Should I make the change?

**Comment by adwait-thattey** [comment]
AFAIU, null and blank are false by default. Please check once

**Comment by masterashu** [comment]
Okay, my bad since it was storing empty strings `''` I thought otherwise.

**Comment by adwait-thattey** [comment]
If we are doing using serializers, it should not store empty strings too.

**Comment by masterashu** [comment]
We can add validators to check for empty strings.

**Comment by adwait-thattey** [comment]
No I mean, by default it should not allow blank strings as blank is False

**Comment by masterashu** [comment]
I believe that was occurring since I made an instance using the console.

**Comment by masterashu** [comment]
This issue should be closed.
The issues are not closing because the default branch is master.
![image](https://user-images.githubusercontent.com/39612799/81491214-2b314900-92a9-11ea-9ba7-e8e11cb4d975.png)

**Comment by adwait-thattey** [comment]
Ya That's fine. We will close manually
Thanks
