### ISSUE TITLE
Add more details to readme

### ISSUE THREAD

**Issue by adwait-thattey** [hardlyhuman/TFExplorer#3]
Add more details to the readme like what the project aims to do, etc.
Also, add a badge for travis

**Comment by siddharth25pandey** [comment]
What we have to write in for the project details and how can I add a badge for travis?

**Comment by adwait-thattey** [comment]
Hello
The Readme should contain details about the project

You can start by writing a few lines about the project, maybe something along the lines "tfexplorer enables developers to quickly find relevant TensorFlow APIs for their needs" 

Then you can write that this is the repo for the backend and write about the tech stack we are using 

Then you can provide a link to contribution guidelines document for those who wish to contribute. 

Travis is a tool we are using for Continuous Integration
You can view project details here https://travis-ci.org/github/hardlyhuman/TFExplorer
There you will find a badge like "Build Passed" in black-green. We want that same badge in the readme near the title of the project. Click on that badge and you should get the Markdown Code to include in the readme

You can also add a telegram badge with the link to the group. Use the image [here](https://patrolavia.github.io/telegram-badge/chat.png) and add a link to the telegram group so that anyone clicking on the image will get redirected to the group. 

Add telegram badge after the Travis badge

**Comment by adwait-thattey** [comment]
Linked PR #9 merged

Closing this issue. 
Will revive again later if needed
