### ISSUE TITLE
Add rest framework specific settings

### ISSUE THREAD

**Issue by adwait-thattey** [hardlyhuman/TFExplorer#6]
There are a bunch of things that need to be added to `settings.py` for `django-rest-framework`. 

Please add these. You will find relevant settings in the documentation of django-rest-framework.

**Comment by ghost** [comment]
i wanna add setting for djnago rest framework.

**Comment by adwait-thattey** [comment]
Please add in settings.py and start a PR. I will review.
Thanks!

**Comment by adwait-thattey** [comment]
@anu725053 Please try to open PR by tonight. There is another PR waiting for this

**Comment by adwait-thattey** [comment]
Associated PR #12 Merged
Thanks
