### ISSUE TITLE
setup token based auth

### ISSUE THREAD

**Issue by adwait-thattey** [hardlyhuman/TFExplorer#7]
Setup token-based auth system. 
Use the library [django-rest-framework-simple_jwt](https://github.com/SimpleJWT/django-rest-framework-simplejwt)

This should be done after User models are created, currently in issue #4

**Comment by masterashu** [comment]
Will setup the User Models #4 and this.

**Comment by adwait-thattey** [comment]
Okay.
I will assign both issues.

**Comment by masterashu** [comment]
It is also closed.
